backport: adding example and clarification (#357)
bluebanquise/bluebanquise pull request #377
Opened 2020-09-21 16:49 UTC by bouriquet

* adding example and clarification

* miscalculation

* precision

* clarification readme

* Update readme.rst

* indentation

* deletion of size indications

* adding example for option 4

* bad unit

* Update readme.rst

* clarification

* clarification, correction, change command

* Update readme.rst

* Update roles/addons/diskless/readme.rst

Co-authored-by: Bruno Travouillon <devel@travouillon.fr>

* Update readme.rst

a blank line is missing => ok
5G is more user-friendly. => ok

* Update readme.rst

Co-authored-by: Bruno Travouillon <devel@travouillon.fr>
(cherry picked from commit 14c445719e871b5fbb8d7908fdad742e47063a18)

2020-09-21 17:22 UTC, btravouillon approved these changes

2020-09-22 06:36 UTC, oxedions commented
Please backport also https://github.com/bluebanquise/bluebanquise/commit/03484641b8b26ed588201d006b8d9e0fe9e40c8e in this PR.

2020-09-22 06:37 UTC, oxedions requested changes
Please backport also https://github.com/bluebanquise/bluebanquise/commit/03484641b8b26ed588201d006b8d9e0fe9e40c8e in this PR.

2020-09-22 11:40 UTC, btravouillon approved these changes

2020-09-22 11:52 UTC, oxedions approved these changes
Dear @bouriquet 

Thanks for this BP.

Merging

2020-09-22 11:52 UTC, merged