Feat: Adding ssh ProxyJump to ssh_master template
bluebanquise/bluebanquise pull request #395
Opened 2020-10-01 07:42 UTC by oxedions

Adding icebergs ssh ProxyJump capability in ssh_master
Adding a defaults value to disable by default ssh jump

2020-10-03 14:12 UTC, oxedions commented on roles/core/ssh_master/defaults/main.yml
> +icebergs_system_enable_ssh_jump: false
Yes, you are right. Forgot 🙂

2020-10-03 14:12 UTC, oxedions commented on roles/core/ssh_master/readme.rst
> +In case of issue, try adding verbosity to the ss invocation to investigate (-vvv).
Good catch !

2020-10-06 13:24 UTC, oxedions commented
Missing changelog

2020-10-06 19:24 UTC, btravouillon requested changes
There is an error in the readme.

2020-10-09 08:14 UTC, oxedions commented on roles/core/ssh_master/readme.rst
> +* icebergs_system_enable_ssh_jump
Please have a look on last commit. I updated 2 variables names, to comply with standards.

2020-10-13 21:08 UTC, btravouillon submitted a review, later dismissed
Looks good to me. 👍

2020-10-14 08:23 UTC, merged