Oxedions/move addons
bluebanquise/bluebanquise pull request #547
Opened 2021-04-01 20:17 UTC by oxedions

Remove addons -> community
Keep some addons into core
Delete nic

2021-04-01 23:05 UTC, btravouillon requested changes

2021-04-01 23:05 UTC, btravouillon commented on resources/packaging/bluebanquise.spec
>  * Tue Apr 14 2020 strus38 <indigoping4cgmi@gmail.com>
The changelog is unordered ?!? Your change is correct, but last line is not. Could you use this PR to reorder the changelog?

2021-04-02 00:32 UTC, btravouillon commented on resources/examples/simple_cluster/playbooks/computes.yml
> +      tags: nic_nmcli
On second thought I believe we should keep legacy `nic` until next major release (2.0), with a deprecation notice.
The change of the role may have an impact on users who already configured their system and rely on the role `nic` to configure their network interfaces.

2021-04-02 13:30 UTC, oxedions commented on .github/TEST_MATRIX.md
> +|![addons/clustershell unit testing](https://github.com/bluebanquise/bluebanquise/workflows/core/clustershell%20unit%20testing/badge.svg)             | x | x | x |
I updated the link but not the string on the left. Corrected.

2021-04-02 13:37 UTC, oxedions commented on roles/core/nic_nmcli/vars/main.yml
> +nic_nmcli_role_version: 1.3.0
Change was made on my local clone, I forgot to remove it. Reverted to previous one, will do the new one in a separate PR.

2021-04-02 13:47 UTC, oxedions commented on resources/packaging/bluebanquise.spec
> +find roles/core -maxdepth 2 \( -name 'molecule' -o -name '.ansible-lint' -o -name '.yamllint' \) -print0 \
Done. I kept the - in addition to the _ in the ansible.cfg for now.

2021-04-02 14:19 UTC, btravouillon commented on .github/TEST_MATRIX.md
> +|![core/clustershell unit testing](https://github.com/bluebanquise/bluebanquise/workflows/core/clustershell%20unit%20testing/badge.svg)             | x | x | x |
```suggestion
|![core/clustershell unit testing](https://github.com/bluebanquise/bluebanquise/workflows/core/clustershell%20unit%20testing/badge.svg)              | x | x | x |
```

2021-04-02 14:19 UTC, btravouillon commented on .github/TEST_MATRIX.md
> +|![core/root_password unit testing](https://github.com/bluebanquise/bluebanquise/workflows/core/root_password%20unit%20testing/badge.svg)           | x | x | x |
```suggestion
|![core/root_password unit testing](https://github.com/bluebanquise/bluebanquise/workflows/core/root_password%20unit%20testing/badge.svg)            | x | x | x |
```

2021-04-02 14:20 UTC, btravouillon commented on .github/TEST_MATRIX.md
> +|![core/clustershell unit testing](https://github.com/bluebanquise/bluebanquise/workflows/core/clustershell%20unit%20testing/badge.svg)             | x | x | x |
To align columns in raw file.

2021-04-06 08:20 UTC, oxedions commented
Seems ready. After that one, I will PR the new nmcli version and the RHEL likes.

2021-04-06 14:15 UTC, btravouillon approved these changes
Looks good to me. 👍

2021-04-07 07:19 UTC, merged