Fix: diskless - Update readme.rst regarding GPG keys
bluebanquise/bluebanquise pull request #642
Opened 2021-12-02 09:58 UTC by oxedions

Fix issue #384

2021-12-02 10:02 UTC, hmeAtos requested changes

2021-12-02 10:02 UTC, hmeAtos commented on roles/core/diskless/readme.rst
> +* Generate a new nfs staging image : A staging image is the base image. You must not boot onto a stagging image but firstly create a golden image from it and boot on the golden image specific filesys
```suggestion
* Generate a new NFS staging image : A staging image is the base image. You must not boot into a staging image but firstly create a golden image from it and boot on the golden image specific filesystem (Created with option 3).
```

2021-12-02 10:17 UTC, hmeAtos requested changes

2021-12-02 10:17 UTC, hmeAtos commented on roles/core/diskless/readme.rst
> +* Generate a new nfs golden image from a staging image : Create a golden image from previously created staging image.
```suggestion
* Generate a new NFS golden image from a staging image : Create a golden image from previously created staging image.
```

2021-12-02 13:41 UTC, oxedions commented
Thanks a lot @hmeAtos !! 😊

2021-12-04 14:52 UTC, johnnykeats approved these changes

2021-12-06 22:25 UTC, ginomcevoy approved these changes
Looks good to me!

2021-12-07 19:39 UTC, oxedions commented
Thanks guys !
Merging.

2021-12-07 19:39 UTC, merged