Feat: ssh_client - Added more ssh client config options
bluebanquise/bluebanquise pull request #988
Opened 2024-11-13 17:20 UTC by thiagocardozo

Added the extra following options to ssh client configuration:

* ForwardX11Trusted
* StrictHostKeyChecking
* UseRoaming

2024-11-18 14:38 UTC, oxedions requested changes
Dear @thiagocardozo 

Thank you for this PR.
Its ok for me, can you update the collection version, this time (x.y.z) y, because its an added feature :blush:

2025-02-27 09:37 UTC, oxedions approved these changes
Dear @thiagocardozo 

Many thanks for this PR ! :blush: 
Ok for me !

2025-02-27 09:41 UTC, oxedions commented
There seems to be some conflicts, but I cannot see where... Weird

2025-03-13 19:14 UTC, thiagocardozo commented
Hello, the conflicts are about the versioning in REAME and galaxy files.

2025-03-17 14:22 UTC, thiagocardozo commented
There are changes from ginomcevoy/smc-2.0 that need to be merged first.

2025-03-17 14:59 UTC, closed without merging